#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Yandex_Translator.Resource", IsApplication=true)]

namespace Yandex_Translator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::OkHttpClient.Resource.String.library_name = global::Yandex_Translator.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btnAddToFav = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int btnSwapLngs = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int btnTranslate = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int etTextFrom = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int etTextTo = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int tvLngFrom = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tvLngTo = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int btn_add_to_fav = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int btn_swap_text = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int btn_translate = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int from_hint = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int from_text = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int to_hint = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int to_text = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
